# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.hl7parser:
        class: AppBundle\Service\HL7Parser

    app.database_writer:
        class: AppBundle\Service\DatabaseWriter
        arguments: ['@doctrine.orm.entity_manager']